name: 'Build'

on:
  push:
    branches: [main]
  pull_request:

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: SDL 2
            flags: '-DNBC_PLATFORM=sdl2 -DBC_GFX_API=OGL'
            packages: 'libsdl2-dev'
    name: Linux (${{ matrix.name }})
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt-get install -y ${{ matrix.packages }}
      - name: Build
        run: |
          cmake -B build ${{ matrix.flags }}
          cmake --build build
