name: 'Build'

on:
  push:
    branches: [main]
  pull_request:

jobs:
  linux:
    name: Linux (SDL 2)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-missing libsdl2-dev
      - name: Build
        run: |
          cmake -B build -DNBC_PLATFORM=sdl2 -DBC_GFX_API=OGL
          cmake --build build
